### ISSUE TITLE
v1 Specs

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/pickr#1]
**Requirements**
- Bind to input `$('input').pickr();
- On focus, show picker
- On blur, hide picker
- On selection, hide picker
- Option to show 1-3 months at a time
- Next/prev buttons to cycle through months
- Show selected month at top
- Click on selected month to go back to today
- Highlight today
- Option to disable previous date selections
- Custom date format for input field
- Less mixin to style

**Tech Reqs**
- Fidel
- date format lib? (pull out into separate lib from weekly if needed)
- moment?

**Inspiration**
- http://kayak.com
- http://amsul.ca/pickadate.js/

**Future Ideas**
- select date ranges
- angular library

**Comment by jgallen23** [comment]
@dawnerd want to take a stab at this today?

**Comment by dawnerd** [comment]
Where do you want the time logged?

**Comment by dawnerd** [comment]
You only want this to select one date or a range of dates (like kayak)?

**Comment by jgallen23** [comment]
one date for the first version
