### ISSUE TITLE
when displaying inline, full width and user zooms in or out on browser, it wraps

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/pickr#23]
if there is no easy fix, we can just not make it 100% width, but lets take a look.

![image001](https://cloud.githubusercontent.com/assets/27936/4739681/97c63eae-5a06-11e4-8dd9-0c54da347e1f.jpg)

**Comment by jgallen23** [comment]
@dawnerd still happening

![screen shot 2014-10-31 at 11 59 50 am](https://cloud.githubusercontent.com/assets/27936/4866884/23a50074-6130-11e4-8063-daf51616d083.png)

**Comment by dawnerd** [comment]
Hmm, are you doing anything different to the examples at all?

**Comment by jgallen23** [comment]
no, just loaded up example and then zoomed to 90%

**Comment by jgallen23** [comment]
I think it's a rounding issue

**Comment by jgallen23** [comment]
any reason we didn't go % width?

**Comment by dawnerd** [comment]
It should be, my change checks if the width is a % and does math based on that. Measurements are slightly different when doing pixels.

**Comment by jgallen23** [comment]
looks like the day width is set as px.  I think if we did border-box and % it might fix the zoom issue

**Comment by jgallen23** [comment]
outside width could be px or % and it should "just work"

**Comment by dawnerd** [comment]
Changed it to be just percents for the days and it seems to work now. Was able to reproduce and it was only breaking when zooming out.

**Comment by jgallen23** [comment]
this works perfectly!  we should do this for the non-inline as well

**Comment by jgallen23** [comment]
well shit.  doesn't work perfectly.  empty spaces are collapsing.  it works perfectly in the example.  I think it's because the site we have it on has a pretty aggressive reset.

![screen shot 2014-11-03 at 10 21 34 am](https://cloud.githubusercontent.com/assets/27936/4887637/429485ba-6386-11e4-9c4d-30f78d177b7c.png)

**Comment by dawnerd** [comment]
I cant seem to replicate it, do you know what styles are being applied that change the width?
