### ISSUE TITLE
option for multi select

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/pickr#9]
be able to select multiple dates.  Thinking it could be an option that could look like `{ multiselect: true }` or `{ multselect: 2 }` (to limit to just two dates)

**Comment by Antonio-Laguna** [comment]
How should this work? I mean in terms of updating the input, should we add a class to state something is being selected, etc?

**Comment by jgallen23** [comment]
Not sure.  Any suggestions?

**Comment by Antonio-Laguna** [comment]
Perhaps a use case would be great. I haven't seen any pickers that can select more than one date.

**Comment by jgallen23** [comment]
Any time you are scheduling a flight. You select the time you want to leave and time you want to come back. I also want to support selecting as many as they want (different use case). It would probably be easier to just support this in inline mode, otherwise it won't know when to close.

**Comment by Antonio-Laguna** [comment]
When you schedule a flight then you normally have two inputs, right?

**Comment by jgallen23** [comment]
No. See virgin america. No inputs. This will be used inline
